services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    ports:
      - "3001:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
    environment:
      - ../../.env
    command: ["npm", "run", "dev"]
