services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    ports:
      - "3000:3000"
    volumes:
      # Monta el código fuente para desarrollo
      - ../../:/app
      # Mantén node_modules separado como volumen para evitar conflictos
      - /app/node_modules
    environment:
      # Usa un archivo .env para las variables de entorno
      - ../../.env
    command: >
      sh -c "
      if [ -f package-lock.json ]; then npm install;
      elif [ -f yarn.lock ]; then yarn install;
      elif [ -f pnpm-lock.yaml ]; then pnpm install;
      fi &&
      npm run dev"
    depends_on:
      - postgres
    networks:
      - portafolio

  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_portafolio:/var/lib/postgresql/data
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - portafolio

volumes:
  postgres_portafolio:
  node_modules:

networks:
  portafolio:
