services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
    environment:
      - ../../.env
    command: ["npm", "run", "dev"]
    depends_on:
      - postgres
    networks:
      - portafolio

  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_portafolio:/var/lib/postgresql/data
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - portafolio

volumes:
  postgres_portafolio:

networks:
  portafolio: