name: Nextjs.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    env:
      NEXT_PUBLIC_API_URL: NEXT_PUBLIC_API_URL

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-build-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies if needed
      run: |
        if [[ ! -d "node_modules" || $(git diff --name-only HEAD~1..HEAD | grep -E "package.json|package-lock.json") ]]; then
          echo "Installing dependencies..."
          npm install
        else
          echo "Dependencies are up to date."
        fi

    - name: Build the application if there are changes
      run: |
        if [[ $(git diff --name-only HEAD~1..HEAD | grep -E "src/|pages/|components/") ]]; then
          echo "Building application..."
          npm run build
        else
          echo "No changes in code, skipping build."
        fi

    - name: Reload PM2
      run: pm2 reload 0
